// <auto-generated />
namespace Base.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EntityRoomAddedd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EntityRoomAddedd));
        
        string IMigrationMetadata.Id
        {
            get { return "201512121241183_Entity Room Addedd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
